spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_currency_db
    username: postgres
    password: 1995
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
    show-sql: false
crypto_currency:
  watcher:
    open_api: coin_lore
